import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Grimox App',
    description: 'Generated by Grimox CLI',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
